apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: graphtuitous
    app.kubernetes.io/part-of: app-graphtuitous
  name: graphtuitous
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: graphtuitous
      app.kubernetes.io/part-of: app-graphtuitous
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: graphtuitous
        app.kubernetes.io/part-of: app-graphtuitous
    spec:
      containers:
      - image: quay.io/shbose/graphtuitous:sbose78-patch-10-c8426005d8683bac048bc10f4df0bda50858e5d2
        imagePullPolicy: Always
        name: graphtuitous
        ports:
        - containerPort: 8080
        resources: {}
      serviceAccountName: default
status: {}
