apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: graphtuitous-gitops
    app.kubernetes.io/part-of: app-graphtuitous-gitops
  name: graphtuitous-gitops
  namespace: dev
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: graphtuitous-gitops
    app.kubernetes.io/part-of: app-graphtuitous-gitops
status:
  loadBalancer: {}
