apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: demo-cicd
spec:
  encryptedData:
    password: AgCJPYtouEnQYlLEGeI10tAmEXuQaBN4DS7zPa3GtwwJaP2dO5RJV4ryQ0tCKwAgpUFeMUFmhDMkRwGh5r0VUaBicUA+f0o3GoAp2QGXNFAP5HgxfrTnUgns8wEX74Vx4qNuasOWKyWF/qnxyL5KZBgKj6GAfE/PHVqJtXwYui/LiEOW639g7JgTSOk1eV7BT8gX3Kr2RwFthqsXPi2tpy3qiSSMR591oqCYZsEWnhZKnIIXvH4yalKmyeGde+4cbEJWVFGBsreimmQU4YW7UVAVqvr4fgI82D/8p7Ox0H8pz6WmzhKLI6zLfj7xlaKSuM0Gk+GTMm0REN5Cux9R1t+BqtMTuajsJh4RPfQgd5gkxkNJZocNUK0XSvgMxgT10LZcvFis7xcmNJ6103IKPvhbLAy1G1V0GKWSoRv2Ng97ZieVXaCbFtaT6eBzyNyBhFvfq91N0/UJSWm/9UzA7uZVsGYtTcfFyWpH/GJWr/WbkphiaKmzf8rp591I/Az4CrxTpbQZdU1l8rkTG5S6TTc6tGyZKV5aHphCZbyZjTIRffDEgH7G819aqPLqfbklFfI51ZK1tJ2o4PmT3xChhNFqlRsRg6fatFgVdaezgtruM2IasEzPcHGe5r7yw6TwONDMeda9bHF8dmLFN0OE3ZumoOfqEMizbThxdxStKHieS6pNaZ/Ll9OT6HgEtwde9Hj/accOesiC/BkyREUqWAUhmvFkYbcpVg7d6OYKjvToYdKu5r/88AMM
    username: AgAGLhx63fAARlO9Kh0w2sI6ZWARdraMaND7B3bCEEnGB1WH0nMkMoXxkTMtMDIjQUwo502FeCiuNXgXJOCVTQqeZho7zAqQCfnE3b7hdVCGvOUQKd8M3MKtrRQfphC9Ai6R/Qy55U9tdyLQWiypUX6AP1k8A4tBRORLzo1xivLcol57fdtD7Q3XlLgLKPvmwG7I1VA3KMTXpC443nlA8S/vgMf+sefZUhqNqAHyOviSLMEXJXX+zfJzy8sRQnQw/U1IjLWeWLHOkImaen3VLgiKmDGNcscs0GTZ0+SNOdbKXo1JEKW7H6ulJnXezjHP26RwlcNeEn00nMCjBoX3ngSIlyjGpkjE3+RiAkGFTrlrFtpLa/vjsvoKcIv038Gfw7Dih2EVBioNYMxUVOaPyDc01HQL2MgOPJOHAoNzLWwLK4NkUQiOW7GXD0QQ+V9yWC3ta3nelSK1o7KhmZZatkcnZVuzuALcVDjPzTbU2xqy5idyx9/SXUIjSb9Q3x1GO9OXRDUrP5AK6EPLmhcYl0DUEtg5SFm1ba9s0oDAVVxqmTGQWNv2sQDFJx10i3mQp4d6FN1MQo2Oo0LIaOPLyMwhyYAXO25wBFexcQ0Hw7XKfIPucgKX0nbfnVG5GAGfQrsN4lDbPUfZ8vgxlcrIXEL1TlY7ApRobO6mukeehZ/K62Zbwpkzmv+AEm+cNNBuWFACd8b7XQI=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: demo-cicd
    type: kubernetes.io/basic-auth
