apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgDJiSdXLskz07Dpik5acosD0d5WkRXw0Uzr/TJ0tiYX8fwVtWjuyWYQPZyKWFZgpn7Em61WJW1IRDfhjKrzALyNpYRBXEnJLFxMUm4lxD5hjwzsxgrBdq4uqzbbVQxWMnUJfHtastSUX7FowcDmhAA3gY7HP+4anPp6QhGyCDa2t8y5Fc7OwK7mVQ0YuUq0s0DJ25ZX8CsPs/T7CDKqfjSffACOaU7zxLAJOJIUvUCK7221rCZ53IJN7KTBht3sjudmt+P+HKcYsxSIfwhF9KzmOwwTnRgDq2SOxe2Hajr9PE1JK3h90awERJPIm4JNdziv00vrhds5oRlq5fvgEUqGHMj+q+Fssyuys2wqWOaBNOi0pmSFLfbnwMdSv8y3cV2pRnhbozX/AeJw682BrDPwledJwBpsfUQD/5fV4qvfE2lvFKhuiYidfEgbb8ZdiP1gkT/kEnjZ+ElxUw0LXCi2Vx5Ai1iKp4WoERj178X8U940cQOQwtyEKeGDnLIhTBizw/8lx2zR4OxMcl/QAq7gRstw/gLMuREmjYJNDDql0eNMcITlfgvGiXXfrXF+tl2Q+nIfJ26QL9uVR90ztfZ9Rd+kA5hRPbJgD8x+tZiSbGP0RbctXEieRkXY/Ig6GMV32kVfgZtHtDkmLkXLqIBbrVkdcKP/XNPoGYjPUARBv1Qp5oi0czLEm0dy8X8xIiL5Um6FB18NGz+AUaC4S6l3kC/CswfC7yVuQRhBmbAGaXM+dAqRt9LyRbXlpj/YU4Io2pwqdSyoZ/f9sqmU6kZrBL+/NpF2rTm1KIxPTFO4BIhoay/b2g4AdGaKt5yJxsX1Qbei7bfCsbbk+AlqOqIU/G9PDfAM9Vk4cFjU5d1PLCWq2R9yz65ynm0YhG+sIE06PmgweJKvI8xaX+lIADkhcRDHK61/Z8t21f9gYVh3
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
