apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgBeaVKLqaHVgTvrAQ5z6ec4T5Pw+HRia6n6usW/sNSsHHc16aIJS5wBQBudRmCXkICGxpdcEsHJo+s4C2yyZlNJa6IgwKAYyOOo/VnDCkxNAj/8WJA1bph1E+mvTqJtpTrsJrcX7Ku3X0bCdUDnhp/tAQPS0fPtgms5ggcOgCLHbkCP6o88TO6S5ryMqnfiv+bngXQaropPO1eHrJLBt3/9AanakeDD6fb7R58iPEQoy5FUobmkiWQsXgcrUpE7pYwH1e4p4hvb9YsdZKyiIKPBKVA06krzFkOCPV+t97AMCUdeb04Ft8kkwq0ytDJ+QCXnVELp8anEotv6SaQj4BZfSXeHo3NbaISvYZvIatLloZKJan/d0P+Q19c7KFAGnb8r3DCDNmzw/kUaNcSdq+Vf9sNdq8Pibrg3hIu1Z9ry3F4YDOqF7sRuqw0MFqG/ECPm9VanbZHGebfaeBLDKz9OSlJaQRZiZpn2Aibuk1CfNkvvAMDQu6gC+M6o2aa4XOi+WJXGsoNXUVGGCRIB5LwoealiCI62Gse081nYbAjUaTj5ef/4qO61yz5912JWme4reqIx4dYgHyzS0BGuYL+oZbtiP0lBLga9F43X85JiOvZzZ/iuDH3KsDJI4mZ3B2yrPawnG+0ZE1Ent85MUwi8weNhIEFCG59PuIVk2iO72ZyH5oH/NtM42S+FjA9sr2/9gnAqr260HHbtfStfqrl+wysgN67AbZbXBrHnfEnfDCMJ9ySp6MvsGj/p8YHgPvFHioMLgzD7a1UMF0+qt+GHXLg0iotUn8aM4YdIR6UrFB/90ZOLUm9Tw7V7hYdhFtYDg9uTzTsX71xmFmrHrtTeRxa2e/ZgjnMjNmO0V8RJPh1Q8ZIirpzbLTdix+Xh2XYSEymy8wNAvZdQ5BK0aTlTsyCyH3hWvMyBqG0n/aTgPM6QeDbc/iwkNSsN00o8nzFhi4BLoTc8DSRp7zWaQnjxmIW39w/hcd2q7Be8
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
