apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-access-token
  namespace: cicd
spec:
  encryptedData:
    token: AgAdK6g/jenddSdHs9siTE1clErenSI0TdNoaj3/9kQjH+ZZGgFSIGRjTc7RyzxG4azMO7SqEwKk1fmkY/2xYuiGCDATyhnubWxn6jl/jiXdx6M2eoVpejhyokaVHBN4oX7XrUN+1lQelKQJkg1vEqtJH3JwmzFlyKfGCRM1mKIMxWRwt+wR2yYQsP1GEGIfgZbMTAXLeCq6aMX2AK7OIk1VO1zSGQJ8vgLbQHtSjMbJbbUIYBw+9WOA16Bv5RB/7N6uj00eHwTRhF6Yjs2WB7+Xxb7z2bhb0u86p0biH6xA+y3otIwiwsI7tDszu5SmsP98nrQJSapDWC2/j+PhDJLdnTLTxyx8ktbgc/LWQAwOsrXf3M9D1yuY02r93jbKCkvdlXFCmeff3qSqcoQC+glg5dHaqOTNMTVqBuaR7hKc7wmkEt8egPewvnEW04O6f38SbPxav7kCxtWiyMeUs9u87Byu6QjKBobQ0qSB0/Urs7pyzWz9LifyU+VYoQc0JYA49nnptV43NawE0xX5Ws1sKR1xE8B32xvewbNCFsKOZPRhiWG0S8RUm76ebs+yZ0tgyAiEPhwXO27Vt+fwSUTH1aPxRr7TpL52+Yun5wacQ82Zfmv1cwLMpG6Ueo4cl8BVbQHCYzGxlzh87OWX3BXwYDI8TswDkC4SExyiJqawHgkL6m/hEYEM8shdUn1Q3NfyZGdSQzRc5hfYbmG+ZUIAcZqYzk24E8jDu6qPzU0LbR2xCiXhXDQT
  template:
    metadata:
      creationTimestamp: null
      name: git-host-access-token
      namespace: cicd
    type: Opaque
