apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgDCEe3lTIFImxwECMCI7Q65+jr4T78rIR9FdzJqFjVWPp7SAA9GFywm40J4G0lSQeXagX9oMYAaNvG0LQJgHcN9iN5IGZzIoFT18KknvQJ2D3syCjHqMEe7oK29RTxiKv1B329ByKM+MgoZY8Z7V31Ywk3DvIGk7zjV9l/ohu049OzXyBZVe7zJ1ybNhfmGniXS1cy0pR2IQZVhWMNc9lZy8vNqi8iAk7HmIAGPa3ci7aakwwmWPDsHSpkFG4uLlYhxAWePV//UA8GubHxRFyOrMBPh1++N3ExIcRy5iA0oPoSoA58Z++w641CAjzfaSVQBIJbB9ErQxvk9rZfirVQf4xFRwh/P2/n4aQgKMytTGcf85SqpFTh6lzjuUCXmXXhyiFHgNI83Zkx/bF2VTzR0dvv0c4UIo7QkM/gdFKRNECWPp0yiQiMKo6hYYsM1af8Ee7oNbAjzh28m/W0S/70K1aPH6ew+yYe4EEOPhz31mD88t/oCFINFeCEqCFbN809QzBnD7WlBERi9ooUKJnZe/AEOtb6pnSFIoD83FgPagezFfcxNHIuGfFyTtS9bPeSH1PjXd2bpAyEQDrSQmmZxmgEFhx6YhOcuqEpL37RnsjXiXB+Wn5i7IbT9VMuiXOtX1S+8mVjCRjblahgUdBjtJqgNIYrkAMutbFtsC2IDSpYtvJcnP+gbqUXjk8xHWdRo4j+XGEY5dZmFQroKr134mGHqKvIOmuXTYHAnR/p9XGyJIWNKXTg+
    username: AgByKa+W3E4juZZQ7PzHLp1DT8HL3z1FbVZvXDlhcFtVEwlRvlI2N+VWENFa7GvnLwmjt2Opo3V/R8SztVkiJggrEefb2eCqpWAGRrHZ+9FA2EAvWreawiAo15dPeTaU2XK7qiwtAAwMbVXv2p7cUgMRt5WmjQlbn4Ze535Ln0bFfYcyV3pJVWkuAPbtd1cOZTkAISv4TguXQUetexLt8nbopW1JL35KfhpVUZEMeHTF2JydknkoacunZmqiNw6l2RNLO3ZBTXG60oy0CBfLuBiUliaAQVmblR7WmLEQE6CFauBpr27mbKn8G1L/FnyMR2HWtYK2wEp3LRIGKz4tVQjZPnbePapueh10dTIpu2EX0SobjZaHxc13/rZHg+WecU9cGyb2Zpo1cf33/j9Xb0J5u6E/QoC2VoJT9El9QlYXunWweysS1beRwdC5uLGUiC2NMCk63FT7uGi9/nOtL4IaNmdVP44dK7HIiGlj2/d9oRqXjAQ/SR/uR9mfmav7S2BHEwNRC3Zumol2WSMPcvDVzGUD9SCZFa2uYDCBAPKqTC4UQrXcCZGVsGPXgcpzmnWm7eNld3SRsq4Y7u6k1IJw4nVMWI3HYDwXWW3m/aFSdMlQEGhJeLNlLLKYCUxDyCmxZ5526lxyv2wIHQoVA+C/Mkk+Z2F9uoCtQ8dcr5iI+VqEURqFkBBXTcLD5MIggZIRNt3AcDs=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
