apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-access-token
  namespace: cicd
spec:
  encryptedData:
    token: AgAKFGYooj0XnbmAap5/8U2gcb+20mDQ0zTtnYfDPwKg0waqB2xSXFfAfs/w9qzX7HnbBADprvR5le2uxkgngPDLtJfTmCB4s5aNRWZGX3DJ+oYz+wa3e9NO6fH5c+aYpK0pJ6+3yE+pxPLnFiKATo2ffAFB1CyzSNkJXTt61QQ5784Y0/x7BxNYCdITEsFehvOe8Cj07UF8KsdOGwW6HN4GPu/GVxYGSue55h/p9O1p4SofQBXiFuwQgJoZdRvElY7xsFozPoEplT+HzWFAOobghLU0QN6abHmN+Wy7cBV+CWO4sp3+jWooxqyqQ5YTuZlVslrWUh6QHmXvMyFNjbo7sL4gRvFpm9DzMzPuwSEpTF4RvP2aTX5KAhvCcEbA9M8XRSQJlI96oVIwdFoV0iSkSDB1Pub3cVwiFgnCTAxsduRhU1DJzwMxD/8vxb9Qnz3igPK3gkYiE7V9jzUiezdcVZejDUGlbp9Y/bA19RK+yYtIYDvGyaemeHwLPe43oV54gBUqHwIf29sXEzGVd9s7Fx/SQUk4Lhg3yhVuhPzStky6ysfBtHuTNY5qeWy1KwP4IuhlOulti5QrEcUslka0OjFAoMM8Qut0X0JNyV1vcuNsCqpp5TPsaxA/aBiaQDMd5i9XqrnhAyPwCD94EMYYM0zgpC3Pl2bc9EvgCt9dqGF4wc1ClvKj61xO+S5TrMaKi4TqTav4rOrCkWlO0qKXqE8lXk5Bwetq17jO9Iy5WfEmQFz0YaGU
  template:
    metadata:
      creationTimestamp: null
      name: git-host-access-token
      namespace: cicd
    type: Opaque
