apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCdJRhqwuidmoEr0scpHM99PIy67nqeo71KVvCrcSztgDVuJr3AEzZ6s9vFUAqKiO5Ulxw2V9gmw97WmOkyf+XmDbDlqZ4tu23qhEYq57Y4ZvtCzwbsSMi2c3lSfRhkZBwt0DWC/a7pS1dQCi71T6dJAxVGjH2nmdCt3miMT251BSQaowV8rRPj5Qf3HJS6eqTs5Mdjx+FhyuuDxYdXdHQfE9lU/7jLyyExs3UubCVNmj7n3VSAAl3V2DuFglK+BbnE7E0eH5VDWueYa5lIVi3UiWzSIc65V6ERGTGK4TPB4qWBMCMpfnBAVzmI9chs7I7a4S0EAbYEBN13OtWJakAQJjAENmS+wqt1fNJaNM88psBwc/dcsFcDNDqvn0iLIzaV9eHWY6CGS2nZkmh5jEY7YP/CODvlE+YXy1PeVQ3Gu3yWhp7VM1QLFD2fHqe21yYrdZWWvGGz81z3Z3mfxcVbR9S5jTxhBUGUgEvkZ6nqtKx4MT3/zTq/0+qMh7rdYYgEIGWCzEnu9bAgvVtcyO5hWg4unvUBSoMjRPS1lxspCMVdPnRHl85zyV0mSsH8P5QFvyUMbiD0hNwEy0RYPzHEyOoXxcREROtWz6IBhQkKEXejtFIvrhwMb52R8KnsXEvSumkxY61BBGuzvBFd2A+zT0ZCyEAdjPU78BNI3oseyWDpajUJjDZwVHG0NqXKr6Y8VStK075dG8hvWIjJZNxPgSU/Jg==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
