apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgA2k+7RPcMyGDs2XZekZ0AlGPNEmpTRMZSxJ19Z2iPGM5BOABaWTLxt/Z9mvQPcR9NCwvbZqu2rckmr7uzGBxXXqjC9yBbNjQiVNrqdTwHJ1tCOHHBz9C78Kh93+kKbus/Ul6CwhZ3Uh4ModyagG8VpicoEDo/9DFzfeHLxq1r/fP54gHKmjO5dD/WIgB2czVE6xTCpsVOTE715oLD4uB360VKA7fJxk69cmJh6rLDfwTJxu/oDf1PVqr4QqgFrUzuEjSrYqHiOew/B174ea+k4RZF8zgWlb6zfLPexqSLN7iWtrtCZBnmBzmEmJel6EAbXclQuzVrB8HiZmDLlxcfb62FTOeU47ZaQIIUH4+ltUL2sbYG5wy+DOOn9avC3pV0z2EjvTZHums6/NyYDHuktuuMGbpqsrDVGXZnrcPLicwv09m+n7064OaZdjmCxArOv/eF0P93A4u+uhZWnepBDdslDyFC1twahGIJ6+JWd4gQOFErVIDI5jzL+6z1t6DnIrfOlT1O+TdeBnD5y7rdQkvTbnogob8MLpR0fjh/APa20GLtjPLjGyW7P2MTJX5UvSN8YKJJaBIOGzbTlJ55oz55fwig7rVJhCMVm3kRYujkm8DAi/K1YRcF9vMLoOOmnogQCOcayT6FXWQ4aaZXbo9P8ip0X7dTvGTlAlGemOGLvvj/FNzaqp+eqzIg9UAZquX5erBiBoXcarP121lOPZo6Iag==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
