apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBKC/tyZ+FAawn49wFL6Csb5RF1Dt485g11EOV6DVamu/GGNeqfHfPl2Rq0+ymMTN5ldJEdWJIrPNjpkAQk7BiTVbULp451h0RukLtgxMuMhYxd2g6nRLCq3R5amzvUW4fscXo++KfQLADmB220pMeUtjZH/SANAtdH71bXwQrOghfTH3J0SL5FC64FN/vg9VZ2l9SXq30UHhsGBWAJx0mbVxeZFtr2QRGHl5ppoI1ltJQZAe72AR9O9uiaUJYJt3ZAB3Dpu/fmDPWDrWMYTCBDxizawHd8x8KgpDTfcIT9sDi7ECmfig6DoB57+Hcn8sKOrFDAYRFku5/bejYY0+WZZAIWoW3EOaEa2aVjcbHjkwCdb1dyCOkyYe/VNc4kTXEoiFIC2IUWs8kCcjCap6pDOLpKJ6Fv1ev01Dvt2I04HH+pdfnr/I3MY+ijU5+DgT9ciHb4uE/9s7N0NeFCij+dx2Fi3I7ARfJkicXf+qoYGXEIpnqe4F0jV9cZrybTiAcaL+J4qI+mqWeo2P1b8MNXpVf4axTEq795WnFt1Ns/GWDacbkxHNjqGAAR8q5xOSTIpHhjbfHk/hFhd9mXe4jNcYn4N9ylzMBAQ1rJZx3jU4N7j0sbqt2zCHvX0JQNfdyOm+wbObE9WhaWI3iLfgmDXy2MDe5w1Pewn18qrirHYqxpQG8pm5tNzKA+Pl9/xRE+DFdf9vGUJZh3vjMV3lYYso9ufQ==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
