apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAK1iI57gmbzb1HKIiuXkQ2FT2d3hh5lve0XK/HhnanOjvbUgjr517mxXsxlBFJt0uDB/l74eppnb1ISDqROydqB9coL6scL06vt/ak+CVwu2WcsDNm43F3b2d/C0W+3Lro4h3tfW0nhRkrlzkuvJMq99h+4EJkL645b2gE8/G29/Y1VeZUxvC0B8GRALnSDcI8ksdAsMbmB2cpooYzAEAwHKnnHOANPexb1PaXhlWleEoxhoLmtOutluRL6YrEyDTdGqeX8VQFvXGnFCx0Io+NpZo+koOibpIVTcP8y1znVQRGHAN2S96/6jvdpzdyQvuxeyP9mYWrRggmTqzjRUIMAs1V4I+uPpGtQzh3E30Akpwb9DSv9L2GSkKgduaFe0qFeq/pZuzmXGldPSbtpbm+rKa8RwfuVr6hm06OFD8/WsqI1PIkVovHp+L+A7yhGMZI7rwfoMbb0hCxI8KksUBPoRGjb7i3JavQ8+Hre1J4sv7eIXDDYE+iJwOOLOh2+zwTyX+Jc21/lbxlt2JodKkIAAtHdVhKpO+H4PWh6FjpOnH0QG8wVQaW0V2hEF/0XxdrzKVShVUMeEkryi3E8qUIrCrNqIeEUxgmU3Etuv6I2+9EESTwcmu5dmx0L9fm2gTR/uPOVEk9kCbS0loOa8ADfnSDJ/mSL/P8zYpybEC2AeAJYyTa+6bZ4JmqgfDKZLkyKnHPmyfqx8yY3DnQX7GawOiuwg==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
