apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: commit-status-tracker
  namespace: cicd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: commit-status-tracker
subjects:
- kind: ServiceAccount
  name: commit-status-tracker
  namespace: cicd
